### ISSUE TITLE
Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by sverhagen** [replicatedhq/dockerfilelint#15]
I think I'm following the instructions, but I'm getting the following error:

	$ ./bin/dockerfilelint ../docker/Dockerfile
	E:\dockerfilelint\lib\reference.js:4
	    'description': `All commands in a Dockerfile require at least 1 argument.
	                   ^
	SyntaxError: Unexpected token ILLEGAL
	    at exports.runInThisContext (vm.js:73:16)
	    at Module._compile (module.js:443:25)
	    at Object.Module._extensions..js (module.js:478:10)
	    at Module.load (module.js:355:32)
	    at Function.Module._load (module.js:310:12)
	    at Module.require (module.js:365:17)
	    at require (module.js:384:17)
	    at Object.<anonymous> (E:\dockerfilelint\lib\messages.js:2:17)
	    at Module._compile (module.js:460:26)
	    at Object.Module._extensions..js (module.js:478:10)

Running from Cygwin.

**Comment by marccampbell** [comment]
@sverhagen it's now possible to run this in a Docker container with:

```shell
sudo docker run -v `pwd`/Dockerfile:/Dockerfile dockerfilelint /Dockerfile
```

Will this work for your needs?

**Comment by tianon** [comment]
You can also use the `stdin` support added in #12! :smile:

```console
$ cat Dockerfile | docker run -i --rm dockerfilelint
```

**Comment by sverhagen** [comment]
The root cause of this issue was having a wrong version of Node, due to what the distro in question had to offer. This has been mitigated by using a Docker image! :+1:
